<?php

namespace Database\Seeders;

use App\Models\Candidate;
use Illuminate\Database\Seeder;

class CandidateSeeder extends Seeder
{
    public function run(): void
    {
        $candidates = [
            ['first_name' => 'Aziz', 'last_name' => 'Karimov', 'nationality' => 'Uzbek', 'date_of_birth' => '1990-05-15', 'place_of_birth' => 'Tashkent', 'occupation' => 'Geriatric Nurse', 'german_level' => 'B2', 'country_of_origin' => 'Uzbekistan', 'status' => 'Active', 'certificate' => 'Nursing Certificate, Tashkent Medical College', 'expose_university_degree' => null, 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'B1'], ['language' => 'Russian', 'level' => 'C1']]],
            ['first_name' => 'Olena', 'last_name' => 'Kovalenko', 'nationality' => 'Ukrainian', 'date_of_birth' => '1988-03-22', 'place_of_birth' => 'Kyiv', 'occupation' => 'Nurse', 'german_level' => 'C1', 'country_of_origin' => 'Ukraine', 'status' => 'Active', 'certificate' => 'BSc Nursing, Kyiv National University', 'expose_university_degree' => 'Bachelor of Science in Nursing', 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'B2']]],
            ['first_name' => 'Maria', 'last_name' => 'Santos', 'nationality' => 'Filipino', 'date_of_birth' => '1992-07-10', 'place_of_birth' => 'Manila', 'occupation' => 'Nurse', 'german_level' => 'B1', 'country_of_origin' => 'Philippines', 'status' => 'Active', 'certificate' => 'Philippine Nursing License', 'expose_university_degree' => 'BSc Nursing, University of the Philippines', 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'C1']]],
            ['first_name' => 'Raj', 'last_name' => 'Patel', 'nationality' => 'Indian', 'date_of_birth' => '1985-11-30', 'place_of_birth' => 'Mumbai', 'occupation' => 'IT Specialist', 'german_level' => 'A2', 'country_of_origin' => 'India', 'status' => 'Active', 'certificate' => 'AWS Certified Solutions Architect, CISSP', 'expose_university_degree' => 'BTech Computer Science, IIT Bombay', 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'C2']]],
            ['first_name' => 'Ioana', 'last_name' => 'Popescu', 'nationality' => 'Romanian', 'date_of_birth' => '1994-02-14', 'place_of_birth' => 'Bucharest', 'occupation' => 'Medical Doctor', 'german_level' => 'C1', 'country_of_origin' => 'Romania', 'status' => 'Active', 'certificate' => 'Romanian Medical Board License', 'expose_university_degree' => 'MD, Carol Davila University', 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'B2'], ['language' => 'French', 'level' => 'A2']]],
            ['first_name' => 'Marko', 'last_name' => 'Petrovic', 'nationality' => 'Serbian', 'date_of_birth' => '1991-08-25', 'place_of_birth' => 'Belgrade', 'occupation' => 'Electrical Engineer', 'german_level' => 'B2', 'country_of_origin' => 'Serbia', 'status' => 'Active', 'certificate' => 'Certified Electrical Engineer', 'expose_university_degree' => 'BSc Electrical Engineering, University of Belgrade', 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'B1']]],
            ['first_name' => 'Amina', 'last_name' => 'Berber', 'nationality' => 'Moroccan', 'date_of_birth' => '1996-12-05', 'place_of_birth' => 'Casablanca', 'occupation' => 'Physiotherapist', 'german_level' => 'B1', 'country_of_origin' => 'Morocco', 'status' => 'Active', 'certificate' => 'Physiotherapy License, Morocco', 'expose_university_degree' => 'Bachelor in Physiotherapy, Mohammed V University', 'anabin_status' => null, 'additional_languages' => [['language' => 'French', 'level' => 'C1'], ['language' => 'Arabic', 'level' => 'Native']]],
            ['first_name' => 'Ana', 'last_name' => 'Lima', 'nationality' => 'Brazilian', 'date_of_birth' => '1989-04-17', 'place_of_birth' => 'São Paulo', 'occupation' => 'Accountant', 'german_level' => 'A2', 'country_of_origin' => 'Brazil', 'status' => 'Active', 'certificate' => 'CPA Brazil, CFC Member', 'expose_university_degree' => 'Bachelor in Accounting, USP', 'anabin_status' => null, 'additional_languages' => [['language' => 'English', 'level' => 'B1'], ['language' => 'Portuguese', 'level' => 'Native']]],
            ['first_name' => 'Giorgi', 'last_name' => 'Beridze', 'nationality' => 'Georgian', 'date_of_birth' => '1993-09-08', 'place_of_birth' => 'Tbilisi', 'occupation' => 'Software Developer', 'german_level' => 'B1', 'country_of_origin' => 'Georgia', 'status' => 'Active', 'certificate' => null, 'expose_university_degree' => 'BSc Computer Science, Tbilisi State University', 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'C1']]],
            ['first_name' => 'Jovana', 'last_name' => 'Nikolic', 'nationality' => 'Serbian', 'date_of_birth' => '1997-01-20', 'place_of_birth' => 'Novi Sad', 'occupation' => 'Nurse', 'german_level' => 'A1', 'country_of_origin' => 'Serbia', 'status' => 'Active', 'certificate' => 'Nursing Diploma', 'expose_university_degree' => null, 'anabin_status' => null, 'additional_languages' => [['language' => 'English', 'level' => 'A2']]],
            ['first_name' => 'Taras', 'last_name' => 'Shevchenko', 'nationality' => 'Ukrainian', 'date_of_birth' => '1986-06-12', 'place_of_birth' => 'Lviv', 'occupation' => 'Welder', 'german_level' => 'B1', 'country_of_origin' => 'Ukraine', 'status' => 'Active', 'certificate' => 'TIG/MIG Welding Certification', 'expose_university_degree' => null, 'anabin_status' => null, 'additional_languages' => [['language' => 'Russian', 'level' => 'C1']]],
            ['first_name' => 'Priya', 'last_name' => 'Sharma', 'nationality' => 'Indian', 'date_of_birth' => '1990-10-03', 'place_of_birth' => 'Delhi', 'occupation' => 'Physiotherapist', 'german_level' => 'B2', 'country_of_origin' => 'India', 'status' => 'Active', 'certificate' => 'BPT, Registered Physiotherapist India', 'expose_university_degree' => 'Bachelor of Physiotherapy, Delhi University', 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'C1']]],
            ['first_name' => 'Denis', 'last_name' => 'Kovalev', 'nationality' => 'Ukrainian', 'date_of_birth' => '1995-03-28', 'place_of_birth' => 'Kharkiv', 'occupation' => 'IT Specialist', 'german_level' => 'A2', 'country_of_origin' => 'Ukraine', 'status' => 'Active', 'certificate' => 'CompTIA Security+, Google Cloud Professional', 'expose_university_degree' => 'BSc Information Technology', 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'B2'], ['language' => 'Russian', 'level' => 'C2']]],
            ['first_name' => 'Fatima', 'last_name' => 'El Mansouri', 'nationality' => 'Moroccan', 'date_of_birth' => '1988-07-15', 'place_of_birth' => 'Rabat', 'occupation' => 'Nurse', 'german_level' => 'B2', 'country_of_origin' => 'Morocco', 'status' => 'Inactive', 'certificate' => 'Nursing License Morocco', 'expose_university_degree' => null, 'anabin_status' => null, 'additional_languages' => [['language' => 'French', 'level' => 'C2'], ['language' => 'Arabic', 'level' => 'Native']]],
            ['first_name' => 'Bogdan', 'last_name' => 'Ionescu', 'nationality' => 'Romanian', 'date_of_birth' => '1992-11-22', 'place_of_birth' => 'Cluj-Napoca', 'occupation' => 'Electrical Engineer', 'german_level' => 'B1', 'country_of_origin' => 'Romania', 'status' => 'Inactive', 'certificate' => null, 'expose_university_degree' => 'BSc Electrical Engineering, Technical University Cluj', 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'B1']]],
            ['first_name' => 'Santosh', 'last_name' => 'Kumar', 'nationality' => 'Indian', 'date_of_birth' => '1984-05-09', 'place_of_birth' => 'Chennai', 'occupation' => 'Medical Doctor', 'german_level' => 'C1', 'country_of_origin' => 'India', 'status' => 'Inactive', 'certificate' => 'MBBS, MD Internal Medicine', 'expose_university_degree' => 'MBBS & MD, Madras Medical College', 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'C2']]],
            ['first_name' => 'Nikita', 'last_name' => 'Petrov', 'nationality' => 'Ukrainian', 'date_of_birth' => '1998-08-30', 'place_of_birth' => 'Odessa', 'occupation' => 'Chef', 'german_level' => 'A1', 'country_of_origin' => 'Ukraine', 'status' => 'Inactive', 'certificate' => 'Culinary Arts Diploma', 'expose_university_degree' => null, 'anabin_status' => null, 'additional_languages' => [['language' => 'Russian', 'level' => 'C1']]],
            ['first_name' => 'Leila', 'last_name' => 'Ahmadi', 'nationality' => 'Moroccan', 'date_of_birth' => '1991-02-11', 'place_of_birth' => 'Fes', 'occupation' => 'Geriatric Nurse', 'german_level' => 'B2', 'country_of_origin' => 'Morocco', 'status' => 'Placed', 'certificate' => 'Geriatric Care Specialist Certification', 'expose_university_degree' => null, 'anabin_status' => null, 'additional_languages' => [['language' => 'French', 'level' => 'B2'], ['language' => 'Arabic', 'level' => 'C2']]],
            ['first_name' => 'Paulo', 'last_name' => 'Ferreira', 'nationality' => 'Brazilian', 'date_of_birth' => '1987-12-19', 'place_of_birth' => 'Rio de Janeiro', 'occupation' => 'Software Developer', 'german_level' => 'B1', 'country_of_origin' => 'Brazil', 'status' => 'Placed', 'certificate' => null, 'expose_university_degree' => 'BSc Computer Science, UFRJ', 'anabin_status' => 'H+', 'additional_languages' => [['language' => 'English', 'level' => 'C1'], ['language' => 'Portuguese', 'level' => 'Native']]],
            ['first_name' => 'Nino', 'last_name' => 'Giorgadze', 'nationality' => 'Georgian', 'date_of_birth' => '1993-04-25', 'place_of_birth' => 'Kutaisi', 'occupation' => 'Accountant', 'german_level' => 'B2', 'country_of_origin' => 'Georgia', 'status' => 'Placed', 'certificate' => 'ACCA Member', 'expose_university_degree' => 'Bachelor in Finance & Accounting, Kutaisi University', 'anabin_status' => null, 'additional_languages' => [['language' => 'English', 'level' => 'B2'], ['language' => 'Russian', 'level' => 'B1']]],
        ];

        foreach ($candidates as $data) {
            Candidate::create($data);
        }
    }
}
